version: '3.7'

services:

#CLIENT FRONT-END

  fantasy-sport-betting-client-app:
    environment:
      - NODE_ENV=development
    volumes:
      - ./fantasy-sport-betting-client-app:/app:ro
    ports:
      - "4200:80"

#SERVER BACK-END:

  fantasysportbettingapp-server:
    container_name: fantasysportbettingapp-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: on-failure
    depends_on:
      - fantasysportbettingapp-mongodb
    ports:
      - "8000:8080"
      - "8001:8081"
    networks:
      - fantasysportbettingapp-network 

#DATABASES

  fantasysportbettingapp-mongodb:
    container_name: fantasysportbettingapp-mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mongo-volume:/data/discount-manager-mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - fantasysportbettingapp-network 

#NETWORK

networks:
  fantasysportbettingapp-network:
    driver: bridge